project:
  type: website
  output-dir: docs

author:
- Nathaniel Giovanni Yomogida, SPT
- name: ChloÃ« Kerstein, SPT

website:
  page-navigation: true
  title: "Alchemy Performance Institute"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Alchemy Archive/archive index.qmd
        text: Archive
      - href: Alchemy Archive/Physiology/physiology index.qmd
        text: Physiology
      - href: Alchemy Archive/Neuro/neuro index.qmd
        text: Neuroscience
      - href: Alchemy Archive/Genetics and genomics/genetics and genomics index.qmd
        text: Genetics & Genomics


bibliography: /Users/nathanielyomogida/Documents/GitHub/Alchemy Performance Institute/Alchemy-Performance-Institute/Alchemy Archive/Bibliography/NGY CAK JVC Bibliography.bib
csl: /Users/nathanielyomogida/Documents/GitHub/Alchemy Performance Institute/Alchemy-Performance-Institute/Alchemy Archive/Bibliography/american-medical-association.csl

format:
  html:
    toc: true
    number-sections: true
    theme:
      light: cosmo
      dark: darkly
    mainfont: helvetica
    css: styles.css
  pdf:
    documentclass: scrartcl
    link-citations: true
    link-bibliography: true
    

